## =============================================================================
## Description
#
# This script contains the code to perform the stability analysis 
# on the empirical data (Appendix I in the paper).
## =============================================================================
# The script is organized as follows:
# 1. Preparation: necessary functions and packages are sourced and loaded.
#
# 2. Create subsets: each subset is generated by randomly sampling 90% 
#    of observations from the original data. 
#
# 3. Run algorithms: CCD, FCI, CCI are applied to each subset 
#    **Note**: it takes quite a long time to run algorithms on all subsets, 
#    and the results are thus saved in `.Rdata` objects.
#
# 4. Compute the frequency: for each cell of adjacency matrix, we construct the
#    frequency table and get the value that occurs the most frequently. Here, we 
#    apply the cut-off, where the most frequent value needs to occur more than 70% 
#    of the time. Otherwise, it is discarded.
#
# 5. Plot the PAGs: given the constructed adjacency matrices from step 4, 
#    we plot the PAGs.
## =============================================================================


## =============================================================================
## 1. Preparation
## =============================================================================
## load necessary packages
library(dplyr)
library(furrr)
library(purrr)
library(pcalg)
# remotes::install_github("KyuriP/CCI_KP")
library(CCI.KP)

source("utils/CCD_fnc.R")
source("utils/plot_fnc.R")
source("utils/data_generating_fnc.R")
source("utils/eval_metrics.R")


## =============================================================================
## 2. Create randomly sampled subsets 
## =============================================================================
plan(multisession)
# specify the number of subsets
subsample_size <- 1000
# create 1000 subsets by randomly sampling 90% from the original data
subsamples <- 1:subsample_size %>% 
  future_map(~depression %>% 
               as_tibble %>% 
               # sample 90% from the original data
               slice_sample(prop=0.9),
             .options = furrr_options(seed=123))


## =============================================================================
## 3. Run algorithms on subsets
## =============================================================================
## run CCD on subsamples
ccd_subsample_dep <- subsamples %>% 
  map(~ccdKP(df=.x, dataType = "continuous", alpha=alpha))
# create an adjacency matrix for PAG
mat_subsample_dep <- ccd_subsample_dep %>% 
  map(~CreateAdjMat(.x, length(.x$nodes)))
# save(mat_subsample_dep, file="data/empirical/mat_subsample_dep.RData")

## run FCI on subsamples
fci_subsample_dep <- subsamples %>%
  map(~fci(list(C = cor(.x), n = nrow(.x)), indepTest=gaussCItest,
           alpha = alpha, doPdsep = TRUE, selectionBias= FALSE,
           labels = colnames(.x)) %>% 
        .@amat
  )
# save(fci_subsample_dep, file="data/empirical/fci_subsample_dep.RData")

## run CCI on subsamples
cci_subsample_dep <- subsamples %>%
  map(~cci(list(C = cor(.x), n = nrow(.x)), gaussCItest, alpha=alpha,
           labels = colnames(.x), p = ncol(.x)) %>% 
        .$maag
  )
# save(cci_subsample_dep, file="data/empirical/cci_subsample_dep.RData")

# load the datasets
load("data/empirical/mat_subsample_dep.RData")
load("data/empirical/fci_subsample_dep.RData")
load("data/empirical/cci_subsample_dep.RData")


## =============================================================================
## 4. Compute the frequencies
## =============================================================================
## construct frequency table per cell
combmat_CCD <- simplify2array(mat_subsample_dep) %>% apply(c(1, 2), table)
combmat_FCI <- simplify2array(fci_subsample_dep) %>% apply(c(1, 2), table)
combmat_CCI <- simplify2array(cci_subsample_dep) %>% apply(c(1, 2), table)


## get the most frequently occurring endpoint
# most frequent endpoints for CCD
freqlistCCD <- combmat_CCD %>% 
  purrr::map_dfr(
    ~as.data.frame(.x) %>% 
      # get the most frequent endpoint along with its frequency
      summarise(val = Var1[which.max(Freq)], 
                freq = max(Freq))
  )
# most frequent endpoints for FCI
freqlistFCI <- combmat_FCI %>% 
  purrr::map_dfr(
    ~as.data.frame(.x) %>% 
      # get the most frequent endpoint along with its frequency
      summarise(val = Var1[which.max(Freq)], 
                freq = max(Freq))
  )
# most frequent endpoints for CCI
freqlistCCI <- combmat_CCI %>% 
  purrr::map_dfr(
    ~as.data.frame(.x) %>% 
      # get the most frequent endpoint along with its frequency
      summarise(val = Var1[which.max(Freq)], 
                freq = max(Freq))
  )


## reconstruct matrix
# adjacency matrix of CCD
adjmat_CCD <- freqlistCCD %>% 
  rowwise() %>% 
  summarize(val = case_when(
    # if more than 70%, assign the corresponding endpoint (val)
    freq > 700 ~ val,
    # if not more than 70%, and not 0 (no edge), then place circle
    freq <700 & val !=0 ~ "1",
    # regardless, if 0 has the highest frequency, then place 0
    .default = "0"
  )) %>% 
  unlist %>% 
  as.numeric %>% 
  matrix(nrow=16, ncol=16) %>% 
  `dimnames<-`(dimnames(combmat_CCD))

# adjacency matrix of FCI
adjmat_FCI <- freqlistFCI %>% 
  rowwise() %>% 
  summarize(val = case_when(
    # if more than 70%, assign the corresponding endpoint (val)
    freq > 700 ~ val,
    # if not more than 70%, and not 0 (no edge), then place circle
    freq <700 & val !=0 ~ "1",
    # regardless, if 0 has the highest frequency, then place 0
    .default = "0"
  )) %>% 
  unlist %>% 
  as.numeric %>% 
  matrix(nrow=16, ncol=16) %>% 
  `dimnames<-`(dimnames(combmat_FCI))

# adjacency matrix of CCI
adjmat_CCI <- freqlistCCI %>% 
  rowwise() %>% 
  summarize(val = case_when(
    # if more than 70%, assign the corresponding endpoint (val)
    freq > 700 ~ val,
    # if not more than 70%, and not 0 (no edge), then place circle
    freq <700 & val !=0 ~ "1",
    # regardless, if 0 has the highest frequency, then place 0
    .default = "0"  )) %>% 
  unlist %>% 
  as.numeric %>% 
  matrix(nrow=16, ncol=16) %>% 
  `dimnames<-`(dimnames(combmat_CCI))


## =============================================================================
## 5. Plot the PAGs
## =============================================================================
# plot the PAGs with most frequently occurring endpoints 
plotAG(adjmat_CCD)
plotAG(adjmat_FCI)
plotAG(adjmat_CCI)
