---
title: "Checklist"
subtitle: 'Planning of the thesis project "Discivering Cyclic Causal Models in Psychological Research"'
author: "Kyuri Park"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format: 
  html:
    embed-resources: true
toc: true
toccolor: "#4169E1"
css: style.css
editor: visual
number-sections: true
keep-md: true
title-block-banner: true
title-block-banner-color: "#F5FFFA"
---

<hr>

# Content Overview {.unnumbered .sectitle}

# Introduction

-   Introduce the network theory <input type="checkbox" name="intronetwork"checked/>
-   Introduce causal discovery <input type="checkbox" name="intro-causaldiscovery"checked/>
-   Introduce the problem --\> What are we going to do? (RQ) <input type="checkbox" name="introprobs" checked/>
-   Connection to the network theory/modeling? <input type="checkbox"/>

# Background

## Graphical Models

-   Provide the basic concepts of graphical models <input type="checkbox" name="intro-graph" checked/>

## Acylic vs. Cyclic Graphs:

-   Explain the required assumptions for constraint-based methods <input type="checkbox" name="intro-assump" checked/>
-   Illustrate difficulties in estimating cyclic graphs compared to DAGs <input type="checkbox" name="cycleprob" checked/>

## Primer on Constraint-based Methods

-   Explain how constraint based methods work <input type="checkbox" name="primer" checked/>

# Causal Discovery Algorithms

-   Introduce three algorithms we are going to examine <input type="checkbox" name="intro-algo" checked/>
-   Table of algorithm overview (assumptions / output representation) and explain the differences <input type="checkbox" name="overview-algo"/>

## CCD

-   Output representation: Markov equivalence class of DCGs (PAG) <input type="checkbox" name="ccdoutput" checked/>
-   CCD trace <input type="checkbox" name="ccdtrace" checked/>

## FCI

-   Output representation: Markov equivalence class of MAG (PAG) <input type="checkbox" name="fcioutput"/>
-   FCI trace <input type="checkbox" name="fcitrace" checked/>

## CCI

-   Output representation: Markov equivalence class of MAAG (PAAG?) <input type="checkbox" name="ccioutput"/>
-   CCI trace <input type="checkbox" name="ccitrace" checked/>

# Simulation

## Simulation Design <input type="checkbox" name="simdesign" checked/>
## Data Generating Process <input type="checkbox" name="datageneration" checked/>
## Evaluation Metrics <input type="checkbox" name="evalmetrics" checked/>
## Simulation results
-   Needs to describe them all in more detail <input type="checkbox"/>


# Emprical Example
##   Introduce empirical data (McNally 2017?) <input type="checkbox" name="mcnally"/>
## Empirical analysis results


# Discussion

## Limitations <input type="checkbox" name="limitations"/>

## Future research <input type="checkbox" name="future"/>

<hr>

# To-dos {.unnumbered .sectitle}

+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| WEEK          | TO-DO                                           | DETAIL                                                                   |
+===============+=================================================+==========================================================================+
| week4         | Work on simulation                              | -   Run CCD, FCI, CCI on an example model.                               |
|               |                                                 | -   Update the code.                                                     |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week5         | Work on simulation                              | -   Run CCD, FCI, CCI on an example model.                               |
|               |                                                 | -   Update the code.                                                     |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week6         | Work on simulation                              | -   Trouble-shooting code.                                               |
|               |                                                 | -   Create summary figures / tables.                                     |
|               | Research seminar                                | -   Seminar about creating an archive.                                   |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week7         | Work on simulation & Consultancy                | -   Trouble-shooting code.                                               |
|               |                                                 | -   Create summary figures / tables.                                     |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week8         | Work on simulation & Consultancy                | -   Trouble-shooting code.                                               |
|               |                                                 | -   Create summary figures / tables.                                     |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week9         | Work on simulation                              | -   Review the results.                                                  |
|               |                                                 | -   Update the simulation design and evaluation metrics.                 |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week10        | Work on simulation & update Methods section     | -   Update the results section.                                          |
|               |                                                 | -   Update the overview of algorithms and description of each algorithm. |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week11        | Work on empirical analysis & Consultancy        | -   Choose an empirical data.                                            |
|               |                                                 | -   Try running the algorithm(s).                                        |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week12        | Work on empirical analysis & Consultancy        | -   Try running the algorithm(s).                                        |
|               |                                                 | -   Trouble-shooting the code.                                           |
|               |                                                 | -   Send a draft (peer feedback)                                         |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week13        | Work on empirical analysis & Discussion         | -   Review the empirical results.                                        |
|               |                                                 | -   Update the results section.                                          |
|               |                                                 | -   Think of limitations/future extensions.                              |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week14        | Update Results & Discussion section             | -   Write a draft.                                                       |
|               |                                                 | -   Ask for feedback.                                                    |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week15        | Update Methods, Results, and Discussion section | -   Rewrite based on the feedback.                                       |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week16        | General Review                                  | -   Write the abstract.                                                  |
|               |                                                 | -   Ask for feedback.                                                    |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week17        | General Review & Research seminar               | -   Review the whole paper.                                              |
|               |                                                 | -   (Do what has not been done yet.)                                     |
|               |                                                 | -   Seminar about writing the abstract                                   |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week18        | Final check & Work on Archive                   | -   Final review.                                                        |
|               |                                                 | -   Make sure the archive is more or less ready.                         |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week19        | <p class="r">                                   | -   Submit the thesis (May 8th, 15:00).                                  |
|               |                                                 | -   Check the archive.                                                   |
|               | Thesis Deadline                                 | -   Make the slides for the defense.                                     |
|               |                                                 |                                                                          |
|               | </p>                                            |                                                                          |
|               |                                                 |                                                                          |
|               | & Work on slides                                |                                                                          |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week20        | <p class="r">                                   | -   Complete the archive (May 15th, 15:00).                              |
|               |                                                 | -   Check the slides for defense.                                        |
|               | Archive Deadline                                | -   Make the poster.                                                     |
|               |                                                 |                                                                          |
|               | </p>                                            |                                                                          |
|               |                                                 |                                                                          |
|               | & Work on poster                                |                                                                          |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week21        | <p class="r">                                   | -   Defense (May 22nd or 23rd)                                           |
|               |                                                 | -   Good luck.                                                           |
|               | Thesis Defense                                  | -   Check the poster.                                                    |
|               |                                                 |                                                                          |
|               | </p>                                            |                                                                          |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+
| week22        | Poster Deadline                                 | -   Join the poster fair (May 30th)                                      |
|               |                                                 | -   The end.                                                             |
+---------------+-------------------------------------------------+--------------------------------------------------------------------------+

: Tentative Schedule
